Repository erhant/circomkit, pull requests merged in 2024-10, with the labels that each got.

#96 Add teardown to cli commands
  src/cli.ts
  src/utils/teardown.ts
Labels: bug

#100 Optimization level null uses Circom default
  src/configs/index.ts
  src/core/index.ts
  src/functions/circuit.ts
  tests/witnessTester.test.ts
Labels: enhancement

#102 example: Bun + SHA256
  .eslintrc.json
  .github/workflows/tests.yml
  README.md
  examples/bun-sha256/.gitignore
  examples/bun-sha256/.vscode/extensions.json
  examples/bun-sha256/.vscode/settings.json
  examples/bun-sha256/README.md
  examples/bun-sha256/bun.lockb
  examples/bun-sha256/circomkit.json
  examples/bun-sha256/circuits.json
  examples/bun-sha256/circuits/main/sha256_32.circom
  examples/bun-sha256/circuits/sha256.circom
  examples/bun-sha256/inputs/sha256_32/default.json
  examples/bun-sha256/package.json
  examples/bun-sha256/src/index.ts
  examples/bun-sha256/tests/sha256.test.ts
  examples/bun-sha256/tsconfig.json
Labels: documentation
